const randomMessages = [
  "The early bird catches the worm.",
  "Actions speak louder than words.",
  "A penny saved is a penny earned.",
  "Beauty is in the eye of the beholder.",
  "Rome wasn't built in a day.",
  "All that glitters is not gold.",
  "The grass is always greener on the other side.",
  "Don't count your chickens before they hatch.",
  "Every cloud has a silver lining.",
  "When in Rome, do as the Romans do.",
  "A stitch in time saves nine.",
  "You can't judge a book by its cover.",
  "Laughter is the best medicine.",
  "Two heads are better than one.",
  "Where there's smoke, there's fire.",
  "The pen is mightier than the sword.",
  "Time heals all wounds.",
  "When the going gets tough, the tough get going.",
  "Don't put all your eggs in one basket.",
  "Better late than never.",
  "Practice makes perfect.",
  "The squeaky wheel gets the grease.",
  "Absence makes the heart grow fonder.",
  "When life gives you lemons, make lemonade.",
  "Fortune favors the bold.",
  "There's no place like home.",
  "You reap what you sow.",
  "Haste makes waste.",
  "Actions speak louder than words.",
  "The best things in life are free.",
  "If the shoe fits, wear it.",
  "A watched pot never boils.",
  "It takes two to tango.",
  "The proof is in the pudding.",
  "Curiosity killed the cat.",
  "Don't bite the hand that feeds you.",
  "Too many cooks spoil the broth.",
  "A rolling stone gathers no moss.",
  "Birds of a feather flock together.",
  "Necessity is the mother of invention.",
  "The bigger they are, the harder they fall.",
  "Out of sight, out of mind.",
  "Easy come, easy go.",
  "All's fair in love and war.",
  "Knowledge is power.",
  "A picture is worth a thousand words.",
  "The apple doesn't fall far from the tree.",
  "A leopard can't change its spots.",
  "You can't have your cake and eat it too.",
  "It's a piece of cake."
];

const generateMessage = () => {
    const randomNum = Math.floor(Math.random() * randomMessages.length);
    const randomMessage = randomMessages[randomNum];
    $("#message").html(`<p>${randomMessage}</p>`);
}